version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: commander
        versions:
          - ">=15.0.0"
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
